# Hardwario YAML file for code generation
# Always use Tab for identation
version: 1
project:
  bundle: com.hardwario.chester.clime
  name: CHESTER Clime
  version: v1.0.3
features:
- bluetooth
- lte
- lorawan
- shell
- led
- button
parameters:
- domain: app
  name: report-interval
  var: report_interval
  type: int
  min: 0
  max: 40000  
  default: 3600
  help: 'Set report interval (default: 3600)'
- domain: app
  name: counter-interval-aggreg
  var: counter_interval_aggreg
  type: int
  min: 32
  max: 324  
  default: 25
  help: 'Set report interval (default: 3600)'
- domain: lte
  name: apn
  type: string
  default: onomondo
  help: Set APN network name
- domain: app
  name: debug-mode
  var: debug_mode
  type: bool
  default: true
  help: 'Set debug mode (T/F)'
- domain: app
  name: temperature
  var: temperature
  type: float
  default: 24.54
  help: 'Set Temperature 0.0f to 50.f'
commands:
- domain: app
  name: send
  callback: app_send
  help: 'Set report interval (default: 3600)'
- domain: app
  name: show
  callback: show
  help: 'Show all configs'
extras:
- CONFIG_BT=n
- CONFIG_APP_INIT_PRIORITY=50