# Hardwario YAML file for code generation
version: 1
project:
  bundle: com.hardwario.chester.counter
  company: 2024 HARDWARIO a.s.
  license: 'SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause'
  name: CHESTER Counter
  version: v1.0.0 
  variant: Counter
features: 
- shell
- accel
- batt
- button
- bluetooth
- buf
- config
- defaults
- edge
- info
- led
- log
- rtc
- therm
- wdog
- entropy_generator
- tinycrypt
- tinycrypt_sha256
- zcbor
- zcbor_stop_on_error
- lte
- x0_a
#- x0_b
#- z
#- tamper
parameters:
- domain: app
  name: interval-sample
  var: interval_sample
  type: int
  min: 1
  max: 86400
  default: 60
  help: 'Get/Set sample interval in seconds (format: <1-86400>).'

- domain: app
  name: interval-report
  var: interval_report
  type: int
  min: 30
  max: 86400
  default: 1800
  help: 'Get/Set report interval in seconds (format: <30-86400>).'

- domain: app
  name: event-report-delay
  var: event_report_delay
  type: int
  min: 1
  max: 86400
  default: 1
  help: 'Get/Set event report delay in seconds (format: <1-86400>).'

- domain: app
  name: event-report-rate
  var: event_report_rate
  type: int
  min: 1
  max: 3600
  default: 30
  help: 'Get/Set event report rate in reports per hour (format: <1-3600>).'

- domain: app
  name: backup-report-connected
  var: backup_report_connected
  type: bool
  default: true
  help: 'Get/Set report when backup is active (format: true, false).'

- domain: app
  name: backup-report-disconnected
  var: backup_report_disconnected
  type: bool
  default: true
  help: 'Get/Set report when backup is inactive (format: true, false).'

commands:
- domain: app
  name: sample
  callback: app_work_sample # This function should be manually created
  help: 'Sample immediately.'

- domain: app
  name: send
  callback: app_work_send # This function should be manually created
  help: 'Send data immediately.'
extras:
# Extras for prj.conf
- CONFIG_ADC_TLA2021_INIT_PRIORITY=60 
- CONFIG_ADC_NRFX_SAADC=n
- CONFIG_ADC_SHELL=n
