# Hardwario YAML file for code generation
version: 1
project:
  bundle: com.hardwario.chester.signal
  name: CHESTER signal
  version: v1.0.0 
  variant: signal
features: 
- shell
- ble
- buf
- defaults
- info
- led
- lte
- s2
- log
- rtc
- therm
- wdog
- entropy_generator
- tinycrypt
- tinycrypt_sha256
parameters:
- domain: app
  name: report-interval
  var: report_inteval
  type: int
  min: 30
  max: 86400
  default: 300
  help: 'Get/Set report interval in seconds (format: <30-86400>).'

- domain: app
  name: measurement-interval
  var: measurement_interval
  type: int
  min: 5
  max: 3600
  default: 300
  help: 'Get/Set measurement interval in seconds (format: <5-3600>).'
