# Hardwario YAML file for code generation
version: 1
project:
  bundle: com.hardwario.chester.scale
  name: CHESTER Scale
  version: v1.0.0 
  variant: scale
features: 
- shell
- accel
- batt
- bluetooth
- button
- buf
- defaults
- info
- led
- log
- rtc
- therm
- wdog
- entropy_generator
- tinycrypt
- tinycrypt_sha256
- zcbor
- zcbor_stop_on_error
- lte
- x3_a
#- x3_b
#- z
#- people_counter
parameters:
- domain: app
  name: channel-a1-active
  var: channel_a1_active
  type: bool
  default: true
  help: 'Get/Set channel A1 activation (format: <true|false>).'

- domain: app
  name: channel-a2-active
  var: channel_a2_active
  type: bool
  default: true
  help: 'Get/Set channel A2 activation (format: <true|false>).'

- domain: app
  name: channel-b1-active
  var: channel_b1_active
  type: bool
  default: true
  help: 'Get/Set channel B1 activation (format: <true|false>).'

- domain: app
  name: channel-b2-active
  var: channel_b2_active
  type: bool
  default: true
  help: 'Get/Set channel B2 activation (format: <true|false>).'

- domain: app
  name: weight-measurement-interval
  var: weight_measurement_interval
  type: int
  min: 5
  max: 3600
  default: 60
  help: 'Get/Set weight measurement interval in seconds (format: <5-3600>).'

- domain: app
  name: report-interval
  var: report_interval
  type: int
  min: 30
  max: 86400
  default: 900
  help: 'Get/Set report interval in seconds (format: <30-86400>).'

- domain: app
  name: people-measurement-interval
  var: people_measurement_interval
  type: int
  min: 5
  max: 3600
  default: 600
  help: 'Get/Set people measurement interval in seconds (format: <5-3600>).'

- domain: app
  name: people-counter-power-off-delay
  var: people_counter_power_off_delay
  type: int
  min: 0
  max: 255
  default: 30
  help: 'Get/Set People Counter power off delay in seconds (format: <0-255>).'

- domain: app
  name: people-counter-stay-timeout
  var: people_counter_stay_timeout
  type: int
  min: 0
  max: 255
  default: 5
  help: 'Get/Set People Counter stay timeout in seconds (format: <0-255>).'

- domain: app
  name: people-counter-adult-border
  var: people_counter_adult_border
  type: int
  min: 0
  max: 8
  default: 4
  help: 'Get/Set People Counter adult border (format: <0-8>).'

commands: 
- domain: app
  name: send
  callback: app_send # This function should be manually created
  help: 'Send data immediately.'

extras:
# Extras for prj.conf
- CONFIG_ADC_TLA2021_INIT_PRIORITY=60 
- CONFIG_ADC_NRFX_SAADC=n
- CONFIG_ADC_SHELL=n
