# Hardwario YAML file for code generation
version: 1
project:
  bundle: com.hardwario.chester.input
  name: CHESTER Input
  version: v1.0.0 
  variant: Input
features: 
- shell
- accel
- adc
- batt
- button
- bluetooth
- buf
- defaults
- edge
- info
- led
- log
- lte
- rtc
- therm
- wdog
- entropy_generator
- tinycrypt
- tinycrypt_sha256
- zcbor
parameters:
  - domain: app
    name: interval-report
    var: interval_report
    type: int
    min: 30
    max: 86400
    default: 1800
    help: 'Get/Set report interval in seconds (format: <30-86400>).'

  - domain: app
    name: event-report-delay
    var: event_report_delay
    type: int
    min: 1
    max: 86400
    default: 5
    help: 'Get/Set event report delay in seconds (format: <1-86400>).'

  - domain: app
    name: event-report-rate
    var: event_report_rate
    type: int
    min: 1
    max: 3600
    default: 30
    help: 'Get/Set event report rate in reports per hour (format: <1-3600>).'

  - domain: app
    name: backup-report-connected
    var: backup_report_connected
    type: bool
    default: true
    help: 'Set backup report connected (default: true)'

  - domain: app
    name: backup-report-disconnected
    var: backup_report_disconnected
    type: bool
    default: true
    help: 'Set backup report disconnected'

  - domain: app
    name: trigger-active-duration
    var: trigger_duration_active
    type: int
    min: 0
    max: 60000
    default: 100
    help: 'Get/Set event active duration in milliseconds (format: <0-60000>).'

  - domain: app
    name: trigger-inactive-duration
    var: trigger_duration_inactive
    type: int
    min: 0
    max: 60000
    default: 100
    help: 'Get/Set event inactive duration in milliseconds (format: <0-60000>).'

  - domain: app
    name: trigger-cooldown-time
    var: trigger_cooldown_time
    type: int
    min: 0
    max: 60000
    default: 10
    help: 'Get/Set trigger cooldown time in milliseconds (format: <0-60000>).'

  - domain: app
    name: trigger-report-active
    var: trigger_report_active
    type: bool
    default: true
    help: 'Set report when trigger is active'

  - domain: app
    name: trigger-report-inactive
    var: trigger_report_inactive
    type: bool
    default: true
    help: 'Set report when trigger is inactive'

  - domain: app
    name: counter-interval-aggreg
    var: counter_interval_aggreg
    type: int
    min: 1
    max: 86400
    default: 300
    help: 'Get/Set counter aggregation interval in seconds (format: <1-86400>).'

  - domain: app
    name: counter-duration-active
    var: counter_duration_active
    type: int
    min: 0
    max: 60000
    default: 2
    help: 'Get/Set event active duration in milliseconds (format: <0-60000>).'

  - domain: app
    name: counter-duration-inactive
    var: counter_duration_inactive
    type: int
    min: 0
    max: 60000
    default: 2
    help: 'Get/Set event inactive duration in milliseconds (format: <0-60000>).'

  - domain: app
    name: counter-cooldown-time
    var: counter_cooldown_time
    type: int
    min: 0
    max: 60000
    default: 10
    help: 'Get/Set counter cooldown time in milliseconds (format: <0-60000>).'

  - domain: app
    name: analog-interval-sample
    var: analog_interval_sample
    type: int
    min: 1
    max: 86400
    default: 60
    help: 'Get/Set analog sample interval in seconds (format: <1-86400>).'

  - domain: app
    name: analog-interval-aggreg
    var: analog_interval_aggreg
    type: int
    min: 1
    max: 86400
    default: 300
    help: 'Get/Set analog aggregation interval in seconds (format: <1-86400>).'

  - domain: app
    name: hygro-interval-sample
    var: hygro_interval_sample
    type: int
    min: 1
    max: 86400
    default: 60
    help: 'Get/Set hygro sample interval in seconds (format: <1-86400>).'

  - domain: app
    name: hygro-interval-aggreg
    var: hygro_interval_aggreg
    type: int
    min: 1
    max: 86400
    default: 300
    help: 'Get/Set hygro aggreg interval in seconds (format: <1-86400>).'

  - domain: app
    name: w1-therm-interval-sample
    var: w1_therm_interval_sample
    type: int
    min: 1
    max: 86400
    default: 60
    help: 'Get/Set ds18b20 sample interval in seconds (format: <1-86400>).'

  - domain: app
    name: w1-therm-interval-aggreg
    var: w1_therm_interval_aggreg
    type: int
    min: 1
    max: 86400
    default: 300
    help: 'Get/Set ds18b20 aggregation interval in seconds (format: <1-86400>).'

commands:
- domain: app
  name: sample
  callback: app_work_sample # This function should be manually created
  help: 'Sample immediately.'

- domain: app
  name: send
  callback: app_work_send # This function should be manually created
  help: 'Send data immediately.'

- domain: app
  name: aggreg
  callback: app_work_aggreg # This function should be manually created
  help: 'Aggregate data immediately'

extras:
# Extras for prj.conf
- CONFIG_ZCBOR_STOP_ON_ERROR=y
- CONFIG_ADC_TLA2021_INIT_PRIORITY=60 
- CONFIG_ADC_SHELL=n

